services:
  - type: web
    name: scoreboard-floorball
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
